#import "common.typ": *
#import "@preview/unify:0.7.1": qty
#set raw(theme: "../evergarden-summer.tmTheme")
#show raw.where(block: true): it => block(
  fill: rgb("#f5efe6"),
  stroke: 1pt + rgb("#2b3034"),
  inset: 8pt,
  radius: 5pt,
  text(fill: rgb("#2b3034"), it),
)

#let symbols = (
  ma: $"ma"$,
)

#problem("1")[
  A virtual memory system has these specifications: Memory access time is
  #qty("50", "ns"). TLB access time is #qty("2", "ns") with a hit ratio of
  #qty("98", "%"). Page fault probability is $10^(-4)$ per page table accesses.
  It takes #qty("5", "ms") to transfer a page from disk to memory or vice versa.

  + What is the effective memory access time? (Consider one-way page transfers.)
  + Assume that #qty("80", "%") of memory accesses are READ operations. What is
    the effective memory access time?
  + We use cache memory to speed up effective memory access time. The cache
    memory has an access time of #qty("10", "ns"), and a hit ratio of 90%. The
    penalty to miss in cache is #qty("200", "ns"). Compute effective memory
    access time with cache memory under the assumptions of parts (a) and (b).
]

The formula for *effective access time* is shown below:

$
  "effective access time" = (1 - p) times #symbols.ma + p times "page fault time"
$

Where #symbols.ma is the _memory access time_, and $p$ is the probability of a
page fault ($0<=p<=1$).

#line(length: 100%)

The constants that we are given are as follows:
- $#symbols.ma = qty("50", "ns")$
- $p=10^(-4)$,
- $"page fault time"=qty("5", "ms") = qty("5e6", "ns")$

The effective access time of the system is $(1 - 10^(-4)) times qty("50", "ns") + 10^(-4) times qty("5e6", "ns") = qty("549.995", "ns")$.

Assuming that #qty("80", "%") of the memory accesses are `READ` operations, the effective memory access time is

#problem("10.1")[
  Under what circumstances do page faults occur? Describe the actions taken by
  the operating system when a page fault occurs.
]

#problem("10.2")[
  Assume that you have a page-reference string for a process with m frames
  (initially all empty). The page-reference string has length $p$, and $n$
  distinct page numbers occur in it. Answer these questions for any
  page-replacement algorithms:
  + What is a lower bound on the number of page faults?
  + What is an upper bound on the number of page faults?
]

#problem("10.2")[
  Consider @table:10.2:page-table. The list of free page frames is `D`, `E`, and
  `F` (where `D` is the head of the list, and `F` is the last). A blank for a
  page frame indicates that the page is not in memory. Convert the following
  virtual addresses to their equivalent physical addresses in hexadecimal. All
  numbers are given in hexadecimal:

  - `9EF`
  - `111`
  - `700`
  - `0FF`

  #figure(
    table(
      columns: 2,
      table.header([*Page*], [*Page Frame*]),
      $0$, table.cell(fill: luma(70%))[],
      $1$, `2`,
      $2$, `C`,
      $3$, `A`,
      $4$, table.cell(fill: luma(70%))[],
      $5$, `4`,
      $6$, `3`,
      $7$, table.cell(fill: luma(70%))[],
      $8$, `B`,
      $9$, `0`,
    ),
    caption: [
      A Page table for a system with 12-bit virtual and physical addresses and
      256-byte pages
    ],
  )<table:10.2:page-table>
]

#problem("10.6")[
  Discuss the hardware functions required to support demand paging.
]

#problem("10.7")[
  Consider the two-dimensional array A, ```c int A[][] = new int[100][100];```,
  where ```c A[0][0]``` is at location $200$ in a paged memory system with pages
  of size $200$. A small process that manipulates the matrix resides in page $0$
  (locations $0->199$). Thus, every instruction fetch will be from page $0$. For
  three page frames, how many page faults are generated by the following
  array-initialization loops? Use `LRU` placement, and assume that page frame
  $1$ contains the process and the other two are initially empty.

  + ```c
    for (int j = 0; j < 100; j++)
      for (int i = 0; i < 100; i++)
        A[i][j] = 0;
    ```

  + ```c
    for (int i = 0; i < 100; j++)
      for (int j = 0; j < 100; i++)
        A[i][j] = 0;
    ```
]

#problem("10.8")[
  Consider the following page reference string:
  `1,2,3,4,2,1,5,6,2,1,2,3,7,6,3,2,1,2,3,6`.

  How many page faults would occur for the following replacement algorithms,
  assuming one, two, three, four, five, six, and seven frames? Remember that all
  frames are initially empty, so your first unique pages will cost one fault
  each.

  - LRU replacement
  - FIFO replacement
  - Optimal replacement
]

#problem("10.9")[
  Consider the following page reference string:
  ```
  7, 2, 3, 1, 2, 5, 3, 4, 6, 7, 7, 1, 0, 5, 4, 6, 2, 3, 0, 1
  ```
  Assuming demand paging with three frames, how many page faults would occur for
  the following replacement algorithms?

  - LRU replacement
  - FIFO replacement
  - Optimal replacement
]


#problem("10.13")[
  Consider a demand-paged computer system where the degree of multiprogramming
  is currently fixed at four. The system was recently measured to determine
  utilization of the CPU and the paging disk. Three alternative results are
  shown below. For each case, what is happening? Can the degree of
  multiprogramming be increased to increase the CPU utilization? Is the paging
  helping?

  #figure(
    table(
      columns: 3,
      table.header([], [*CPU Utilization*], [*Disk Utilization*]),
      [A], qty("13", "%"), qty("97", "%"),
      [B], qty("87", "%"), qty("3", "%"),
      [C], qty("13", "%"), qty("3", "%"),
    ),
  )
]

#problem("10.15")[
  Assume that a program has just referenced an address in virtual memory.
  Describe a scenario in which each of the following can occur. (If no such
  scenario can occur, explain why.)

  - TLB miss with no page fault
  - TLB miss with page fault
  - TLB hit with no page fault
  - TLB hit with page fault
]

#problem("10.16")[
  A simplified view of thread states is ready, running and blocked, where a
  thread is either ready and waiting to be scheduled, is running on the
  processor, or is blocked (for example, waiting for I/O).

  Assuming a thread is in the running state, answer the following questions, and
  explain your answers:

  + Will the the thread change state if it incurs a page fault? If so, to what
    state will it change?
  + Will the thread change state if it generates a TLB miss that is resolved in
    the page table? If so, to what state will it change?
  + Will the thread change state if an address reference is resolved in the page
    table? If so, to what state will it change?
]

#problem("10.17")[
  Consider a system that uses pure demand paging.

  + When a process first starts execution, how would you characterize the
    page-fault rate?
  + Once the working set for a process is loaded into memory, how would you
    characterize the page-fault rate?
  + Assume that a process changes its locality and the size of the new working
    set is too large to be stored in available free memory. Identify some
    options system designers could choose from to handle this situation.
]

#problem("10.18")[
  Consider @table:10.18:page-table. Free page frames are to be allocated in the
  order `9`, `F`, `D`. A blank for a page frame indicates that the page is not
  in memory.

  #figure(
    table(
      columns: 2,
      table.header([*Page*], [*Page Frame*]),
      $0$, `0x4`,
      $1$, `0xB`,
      $2$, `0xA`,
      $3$, table.cell(fill: luma(70%))[],
      $4$, table.cell(fill: luma(70%))[],
      $5$, `0x2`,
      $6$, table.cell(fill: luma(70%))[],
      $7$, `0x0`,
      $8$, `0xC`,
      $9$, `0x1`,
    ),
    caption: [
      A Page table for a system with 12-bit virtual and physical addresses and
      256-byte pages
    ],
  )<table:10.18:page-table>

  Convert the following virtual addresses to their equivalent physical addresses
  in hexadecimal. All numbers are given in hexadecimal. In the case of a page
  fault, you must use one of the free frames to update the page table and
  resolve the logical address to its corresponding physical address.

  - `0x2Al`
  - `0x4E6`
  - `0x94A`
  - `0x316`
]

#problem("10.20")[
  A certain computer provides its users with a virtual memory space of $2^32$
  bytes. The computer has 222 bytes of physical memory. The virtual memory is
  implemented by paging, and the page size is 4,096 bytes. A user process
  generates the virtual address `1112 3456`. Explain how the system establishes
  the corresponding physical location. Distinguish between software and hardware
  operations.
]

#problem("10.21")[
  Assume that we have a demand-paged memory. The page table is held in
  registers. It takes 8 milliseconds to service a page fault if an empty frame
  is available or if the replaced page is not modified and 20 milliseconds if
  the replaced page is modified. Memory-access time is 100 nanoseconds. Assume
  that the page to be replaced is modified 70 percent of the time. What is the
  maximum acceptable page-fault rate for an effective access time of no more
  than 200 nanoseconds?
]

#problem("10.22")[
  Consider @table:10.22:page-table.

  #figure(
    table(
      columns: 3,
      table.header([*Page*], [*Page Frame*], [*Reference Bit*]),
      $0$, `9`, `0`,
      $1$, table.cell(fill: luma(70%))[], `0`,
      $2$, `10`, `0`,
      $3$, `15`, `0`,
      $4$, `6`, `0`,
      $5$, `13`, `0`,
      $6$, `8`, `0`,
      $7$, `12`, `0`,
      $8$, `7`, `0`,
      $9$, table.cell(fill: luma(70%))[], `0`,
      $10$, `5`, `0`,
      $11$, table.cell(fill: luma(70%))[], `0`,
      $12$, `1`, `0`,
      $13$, `0`, `0`,
      $14$, table.cell(fill: luma(70%))[], `0`,
      $15$, `2`, `0`,
    ),
    caption: [
      A Page table for a system with 16-bit virtual and physical addresses and
      4096-byte pages
    ],
  )<table:10.22:page-table>
  The reference bit for a page is set to `1` when the page has been referenced.
  Periodically, a thread zeroes out all values of the reference bit. A dash for
  a page frame indicates that the page is not in memory. The page-replacement
  algorithm is localized LRU, and all numbers are provided in decimal.

  + Convert the following virtual addresses (in hexadecimal) to the equivalent
    physical addresses. You may provide answers in either hexadecimal or
    decimal. Also set the reference bit for the appropriate entry in the page
    table.
    - 0x621C
    - 0xF0A3
    - 0xBClA
    - 0x5BAA
    - 0x0BAl
  + Using the above addresses as a guide, provide an example of a logical
    address (in hexadecimal) that results in a page fault.
  + From what set of page frames will the LRU page-replacement algorithm choose
    in resolving a page fault?
]


#problem("10.24")[
  Apply the (1) FIFO, (2) LRU, and (3) optimal (OPT) replacement algorithms for
  the following page-reference strings:

  - `2, 6, 9, 2, 4, 2, 1, 7, 3, 0, 5, 2, 1, 2, 9, 5, 7, 3, 8, 5`
  - `0, 6, 3, 0, 2, 6, 3, 5, 2, 4, 1, 3, 0, 6, 1, 4, 2, 3, 5, 7`
  - `3, 1, 4, 2, 5, 4, 1, 3, 5, 2, 0, 1, 1, 0, 2, 3, 4, 5, 0, 1`
  - `4, 2, 1, 7, 9, 8, 3, 5, 2, 6, 8, 1, 0, 7, 2, 4, 1, 3, 5, 8`
  - `0, 1, 2, 3, 4, 4, 3, 2, 1, 0, 0, 1, 2, 3, 4, 4, 3, 2, 1, 0`

  Indicate the number of page faults for each algorithm assuming demand paging
  with three frames.
]

#problem("10.29")[
  Consider a demand-paging system with the following time-measured utilizations:

  #figure(
    table(
      columns: 2,
      align: left,
      [CPU utilization], qty("20", "%"),
      [Paging disk], qty("97.7", "%"),
      [Other I/O devices], qty("5", "%"),
    ),
  )

  For each of the following, indicate whether it will (or is likely to) improve
  CPU utilization. Explain your answers.

  + Install a faster CPU.
  + Install a bigger paging disk.
  + Increase the degree of multiprogramming.
  + Decrease the degree of multiprogramming.
  + Install more main memory.
  + Install a faster hard disk or multiple controllers with multiple hard disks.
  + Add prepaging to the page-fetch algorithms.
  + Increase the page size.
]

#problem("10.36")[
  Consider a demand-paging system with a paging disk that has an average access
  and transfer time of 20 milliseconds. Addresses are translated through a page
  table in main memory, with an access time of l microsecond per memory access.
  Thus, each memory reference through the page table takes two accesses. To
  Improve this time, we have added an associative memory that reduces access
  time to one memory reference if the page-table entry is in the associative
  memory. Assume that 80 percent of the accesses are in the associative memory
  and that, of those remaining, 10 percent (or 2 percent of the total) cause
  page faults. What is the effective memory access time?
]

#problem("2")[
  Consider the following string of page references, and assume a 4-frame memory.

  ```
  7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2
  ```

  Complete a figure similar to the one worked in class showing the frame
  allocation for:

  + FIFO (first-in-first-out)
  + LRU (least recently used)
  + Clock
  + Optimal (assume the page reference string continues with
    `1, 2, 0, 1, 7, 0, 1`)
  + List the total number of page faults and the miss rate for each policy.
    Count page faults only after all Frames have been initialized.
]
